name: run-yamllint

on: push

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint with common config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint
        run: yamllint -c .github/linters/.yaml-lint.yaml -f parsable --format standard .github/
