name: test-diff

on:
  push:
    paths:
      - .github/workflows/test-diff.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  job-1:
    name: Running job-1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [Account1, Account2]

    steps:
      - name: Running ${{ matrix.account }} step 1
        run: |
          if [[ "${{ matrix.account }}" == "Account1" ]]; then
            echo "A" > file1.txt
            echo "B" > file2.txt
          else
            echo "A" > file1.txt
            echo "A" > file2.txt
          fi
          diff file1.txt file2.txt

      - name: Running ${{ matrix.account }} step 2
        if: ${{ always() }}
        run: |
          cat file2.txt

  job-last:
    name: Deployment End
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - job-1
    steps:
      - name: Check All Job Statuses
        run: |
          [[ "${{ needs.job-1.result }}" == "success" ]] || exit 1
