name: test-default-branch

on:
  push:
    branches: [ $default-branch ]
    paths:
      - .github/workflow/test-default-branch.yaml

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint with common config
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do something"
      
