name: test-env

on:
  push:
    paths:
      - .github/workflows/test-env.yaml
  workflow_call:
  workflow_dispatch:

env:
  WF_ENV: Available on all jobs

jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - run: aws s3 ls
        continue-on-error: true
      - run: echo "CheckPt2"
  hello2:
    needs: hello1
    runs-on: ubuntu-latest
    steps:
      - run: aws s3 ls
