name: test-check-installed-packages-sizes

on:
  push:
    paths:
      - .github/workflows/test-check-installed-packages-sizes.yaml
  workflow_dispatch:

jobs:
  check-installed-packages-sizes:
    runs-on: ubuntu-latest
    steps:
      - run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -rn
