name: test-new-workflow-not-merged

on:
  push:
    paths:
      - .github/workflows/test-new-workflow-not-merged.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run test-new-workflow-not-merged
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
