name: test-matrix-dynamic

on:
  push:
    paths:
      - .github/workflows/test-matrix-dynamic.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  settings:
    runs-on: ubuntu-latest
    outputs:
      accounts: ${{ env.ACCOUNTS }}
    steps:
      - run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo 'ACCOUNTS=["21","22","23"]' >> $GITHUB_ENV
          else
            echo 'ACCOUNTS=["11","12","13"]' >> $GITHUB_ENV
          fi

  check-env:
    needs: [settings]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.settings.outputs.accounts }}

  job-1:
    needs: [settings]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: ${{ fromJson(needs.settings.outputs.accounts) }}
    steps:
      - name: Run ${{ matrix.account }}
        run: echo ${{ matrix.account }}
