name: test-reusable-workflow

on:
  push:
    paths:
      - .github/workflows/test-reusable-workflow.yaml
  workflow_dispatch:

jobs:
  test-reusable-workflow:
    runs-on: ubuntu-latest
    # uses: USER_OR_ORG_NAME/REPO_NAME/.github/workflows/REUSABLE_WORKFLOW_FILE.yml@TAG_OR_BRANCH
    # at job level, not step level
    uses: kyhau/github-workflow-templates/.github/workflows/test-env.yaml@main
    steps:
      - run: echo "Hello World"
