name: test-matrix-2d

on:
  push:
    paths:
      - .github/workflows/test-matrix-2d.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  job-1:
    name: Run job-1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [Account1, Account2]
        mode: [AMI, DockerImage]

    steps:
      - name: Checking ${{ matrix.account }} ${{ matrix.mode }}
        run: |
          echo "Checking ${{ matrix.account }} ${{ matrix.mode }}"

  job-last:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Check All Job Statuses
        run: |
          echo "${{ needs.job-1.result }}"
