name: test-yamllint

on:
  push:
    paths:
      - .github/linters/.yaml-lint.yaml
      - .github/workflows/test-yamllint.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint with common config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint -c .github/linters/.yaml-lint.yaml .github/

  lint-without-config:
    name: Run yamllint without config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: |
          yamllint -d "{extends: relaxed, rules: {document-start: disable, line-length: disable, truthy: disable}}" .github/
