name: test-matrix-2d

on:
  push:
    paths:
      - .github/workflows/test-matrix-2d.yaml

defaults:
  run:
    shell: bash

jobs:
  job-1:
    name: Running job-1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [Account1, Account2]
        mode: [AMI, DockerImage]

    steps:
      - name: Checking ${{ matrix.account }} ${{ matrix.mode }}
        run: |
        echo "Checking ${{ matrix.account }} ${{ matrix.mode }}"

     - if: ${{ matrix.account ==  'Account2' }}
        name: Running ${{ matrix.account }} step 1
        run: |
          echo "Running ${{ matrix.account }} step 1"

      - name: Running ${{ matrix.account }} step 2
        run: |
          if [[ "${{ matrix.account }}" == "Account1" ]]; then
            echo "Hello Account1"
          else
            echo "Hello Account2"
          fi

      - if: ${{ always() }}
        name: Running ${{ matrix.account }} step 3
        run: |
          echo "Running ${{ matrix.account }} step 3"

  job-last:
    name: Deployment End
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - job-1
    steps:
      - name: Check All Job Statuses
        run: |
          echo "${{ needs.job-1.result }}"
