name: test-add-mask-2

on:
  push:
    paths:
      - .github/workflows/test-add-mask-2.yaml
  workflow_dispatch:
    inputs:
      HELLO1:
        description: Something like a secret
        default: ""

defaults:
  run:
    shell: bash

jobs:
  masking-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::add-mask::${{ inputs.HELLO1 }}"

  test-1:
    needs: [masking-inputs]
    runs-on: ubuntu-latest
    env:
      HELLO1: ${{ inputs.HELLO1 }}
    steps:
      - run: echo ${{ inputs.HELLO1 }}
      - run: echo ${{ env.HELLO1 }}
