name: test-environment-protection

on:
  push:
    paths:
      - .github/workflows/test-environment-protection.yaml

defaults:
  run:
    shell: bash

jobs:
  job-1:
    environment:
      name: production
      url: https://github.com/kyhau/github-workflow-templates
    name: Running job-1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step 1"
