name: test-reusable-workflow

on:
  push:
    paths:
      - .github/workflows/test-reusable-workflow.yaml
  workflow_dispatch:

jobs:
  test-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      # uses: USER_OR_ORG_NAME/REPO_NAME/.github/workflows/REUSABLE_WORKFLOW_FILE.yml@TAG_OR_BRANCH
      - uses: test-env.yaml
