name: test-add-mask-secret
# run-name: "Env: ${{ inputs.env }} Secret Name: ${{ inputs.secret_name }} @ ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: Secret Name
        required: true
        type: string
      secret_value:
        description: Secret Value
        required: true
        type: string

defaults:
  run:
    shell: bash

env:
  SECRET_NAME: ${{ inputs.secret_name }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Mask
        run: |
          SECRET_VALUE=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
          echo ::add-mask::$SECRET_VALUE
          echo SECRET_VALUE=$SECRET_VALUE >> $GITHUB_ENV

      - run: echo $SECRET_VALUE
