name: test-environment-protection

on:
  push:
    paths:
      - .github/workflows/test-environment-protection.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  job-1:
    environment:
      name: production
      url: https://github.com/kyhau/github-workflow-templates
    name: Has environmentc, env secret available
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.TEST_ENV_SECRET }}
  job-2:
    name: No environment, env secret not available
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.TEST_ENV_SECRET }}
