name: test-default-branch

on:
  push:
    branches:
      - main
    paths:
      - .github/workflow/test-default-branch.yaml

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run a job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do something"
