name: test-matrix

on:
  push:
    paths:
      - .github/workflows/test-matrix.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  job-1:
    name: Run job-1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [Account1, Account2]

    steps:
      - name: Run step if account == Account2? ${{ matrix.account }}
        if: ${{ matrix.account == "Account2" }}
        run: |
          echo "Running ${{ matrix.account }} step 1"

      - name: Check if in step-run
        run: |
          if [[ "${{ matrix.account }}" == "Account1" ]]; then
            echo "Hello Account1"
          else
            echo "Hello Account2"
          fi

      - name: Run always
        if: ${{ always() }}
        run: |
          echo "Running ${{ matrix.account }} step 3"

  job-last:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Check All Job Statuses
        run: |
          echo "${{ needs.job-1.result }}"
