name: test-env

on:
  push:
    paths:
      - .github/workflows/test-env.yaml
  workflow_call:
  workflow_dispatch:

env:
  WF_ENV: Available on all jobs
  VAR_PREFIX: Test101
  Test101_VAR: Hello World

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available on all steps
    steps:
      - name: Log env variables
        env:
          STEP_ENV: Available on only this steps
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default ENV variables
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_ENV: ${GITHUB_ENV}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  test-env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ env.{VAR_PREFIX}_VAR }}"

