name: test-multi-set-output

on:
  workflow_dispatch:
    inputs:
      deploystage:
        description: 'Which AWS account to deploy into [dev, prd]?'
        required: true
        default: 'dev'

defaults:
  run:
    shell: bash

jobs:

  common:
    name: Sharing values to diff job
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.vars.outputs.environment }}
      stacksuffix: ${{ steps.vars.outputs.stacksuffix }}
    steps:
      - id: vars
        # if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" == "prd" ]]; then
            echo "::set-output name=environment::prd"
            echo "::set-output name=stacksuffix::"
          else
            echo "::set-output name=environment::dev"
            echo "::set-output name=stacksuffix::-dev"
          fi

  echo-common:
    name: Using values from diff job
    env:
      environment2: ${{needs.common.outputs.environment}}
    runs-on: ubuntu-latest
    needs: common
    steps:
      - run: |
          echo environment=${{needs.common.outputs.environment}}
          echo stacksuffix=${{needs.common.outputs.stacksuffix}}
          echo environment2=${{env.environment2}}

  tests-share-btw-steps-1:
    name: Sharing values with other steps in the same job
    runs-on: ubuntu-latest
    steps:
      - id: VpcInfo
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" == "prd" ]]
          then
            echo "::set-output name=vpcid::vpc-11111111"
            echo "::set-output name=subnetid::subnet-11111111"
          elif [[ "${{ github.event.inputs.deploystage }}" == "dev" ]]
          then
            echo "::set-output name=vpcid::vpc-22222222"
            echo "::set-output name=subnetid::subnet-22222222"
          else
            exit 1
          fi
      - run: |
          echo ${{ steps.VpcInfo.outputs.subnetid }}
          echo ${{ steps.VpcInfo.outputs.vpcid }}
          
  test-empty-value:
    name: Test passing empty value
    runs-on: ubuntu-latest
    steps:
      - id: StackNameVariant
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" != "prd" ]]
          then
            echo "::set-output name=suffix::-dev"
          else
            echo "::set-output name=suffix::"
          fi
      - run: |
          echo "hello${{ steps.StackNameVariant.outputs.suffix }}world"
