name: test-add-mask

on:
  push:
    paths:
      - .github/workflows/test-add-mask.yaml

defaults:
  run:
    shell: bash

jobs:
  mask-before-init:
    runs-on: ubuntu-latest
    steps:
      - name: JOB_1_VAR
        run: |
          echo "::add-mask::$JOB_1_VAR"

  test-add-mask-env:
    name: Test add-mask on env
    runs-on: ubuntu-latest
    env:
      JOB_1_VAR: job_1_val_value
      JOB_2_VAR: job_2_val_value
    steps:
      - name: JOB_1_VAR is not masked
        run: |
          echo "::add-mask::$JOB_1_VAR"

      - name: Expected JOB_1_VAR is masked
        run: |
          echo "$JOB_1_VAR"

  test-add-mask-env-2:
    name: Test add-mask on env 2
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        run: |
          echo "::add-mask::$action_state"
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'

  test-add-mask-step-output:
    name: Test add-mask on step output
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - id: VpcInfo
        run: |
          echo "::set-output name=vpcid::vpc-11111111"
      - run: |
          echo "::add-mask::${{ steps.VpcInfo.outputs.vpcid }}"
      - run: |
          echo ${{ steps.VpcInfo.outputs.vpcid }}
