name: test-multi-set-output

on:
  workflow_dispatch:
    inputs:
      deploystage:
        description: Deployment stage
        type: choice
        default: prd
        options:
          - dev
          - prd

defaults:
  run:
    shell: bash

jobs:

  common:
    name: Sharing values to diff job
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.vars.outputs.environment }}
      stacksuffix: ${{ steps.vars.outputs.stacksuffix }}
    steps:
      - id: vars
        # if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" == "prd" ]]; then
            echo "environment=prd" >> $GITHUB_OUTPUT
            echo "stacksuffix=" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "stacksuffix=-dev" >> $GITHUB_OUTPUT
          fi

  echo-common:
    name: Using values from diff job
    env:
      environment2: ${{needs.common.outputs.environment}}
    runs-on: ubuntu-latest
    needs: common
    steps:
      - run: |
          echo environment=${{needs.common.outputs.environment}}
          echo stacksuffix=${{needs.common.outputs.stacksuffix}}
          echo environment2=${{env.environment2}}

  tests-share-btw-steps-1:
    name: Sharing values with other steps in the same job
    runs-on: ubuntu-latest
    steps:
      - id: VpcInfo
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" == "prd" ]]
          then
            echo "vpcid=vpc-11111111" >> $GITHUB_OUTPUT
            echo "subnetid=subnet-11111111" >> $GITHUB_OUTPUT
            echo "filtervalue=AccountName!=test1 AccountName!=test2" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.deploystage }}" == "dev" ]]
          then
            echo "vpcid=vpc-22222222" >> $GITHUB_OUTPUT
            echo "subnetid=subnet-22222222" >> $GITHUB_OUTPUT
            echo "filtervalue=AccountName=test1 AccountName=test2" >> $GITHUB_OUTPUT
          else
            exit 1
          fi
      - run: |
          echo ${{ steps.VpcInfo.outputs.subnetid }}
          echo ${{ steps.VpcInfo.outputs.vpcid }}
          echo ${{ steps.VpcInfo.outputs.filtervalue }}

  test-empty-value:
    name: Test passing empty value
    runs-on: ubuntu-latest
    steps:
      - id: StackNameVariant
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" != "prd" ]]
          then
            echo "suffix=-dev" >> $GITHUB_OUTPUT
          else
            echo "suffix=" >> $GITHUB_OUTPUT
          fi
      - run: |
          echo "hello${{ steps.StackNameVariant.outputs.suffix }}world"
