name: test-if-conditions
on:
  push:
    paths:
      - .github/workflows/test-if-conditions.yaml
  workflow_dispatch:
    inputs:
      deploystage:
        description: Deployment stage
        type: choice
        default: dev
        options:
          - dev
          - prd

defaults:
  run:
    shell: bash

jobs:
  at-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Do something on this branch ${{ github.ref }} only for prd

  at-step:
    name: Run a step if branch is something
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo This is a branch - ${{ github.ref }}

      - if: ${{ (github.ref != 'refs/heads/main') && (github.event.inputs.deploystage == 'prd') }}
        run: |
          echo Do something on this branch ${{ github.ref }} only for prd

  in-step-run:
    name: Check if-condition inside a step run
    runs-on: ubuntu-latest
    steps:
      - id: vars
        # if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" == "prd" ]]; then
            echo "::set-output name=environment::prd"
            echo "::set-output name=stacksuffix::"
          else
            echo "::set-output name=environment::dev"
            echo "::set-output name=stacksuffix::-dev"
          fi
      - run: |
          echo ${{ steps.vars.outputs.environment }}
          echo ${{ steps.vars.outputs.stacksuffix }}
