name: test-if-conditions
on:
  push:
    paths:
      - .github/workflows/test-if-conditions.yaml
  workflow_dispatch:
    inputs:
      deploystage:
        description: Deployment stage
        type: choice
        default: dev
        options:
          - dev
          - prd

defaults:
  run:
    shell: bash

jobs:
  at-job:
    name: Test if-condition at job
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Do something on this branch ${{ github.ref }} only for prd

  at-job-2:
    name: Test if-not-condition at job
    if: ! ( ${{ github.ref == "refs/heads/main" }} && "${{ inputs.accountEnv }}" == "dev" )
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Do not run this if this is the main branch and is dev

  at-step:
    name: Test if-condition at step
    runs-on: ubuntu-latest
    steps:
      - name: Test step if main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo This is a branch - ${{ github.ref }}

      - name: Test step if non main branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo This is a branch - ${{ github.ref }}

      - name: Test step multi conditions main and prd
        if: ${{ (github.ref == 'refs/heads/main') && (inputs.deploystage == 'prd') }}
        run: |
          echo Do something on this branch ${{ github.ref }} only for prd

      - name: Test step multi conditions with always and prd
        if: ${{ always() && inputs.deploystage == 'prd' }}
        run: |
          echo Do something on this branch ${{ github.ref }} only for prd

  in-step-run:
    name: Test if-condition inside a step run
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]] && [[ "${{ inputs.deploystage }}" == "prd" ]]; then
            echo "CheckPt A - main branch + prd"
            echo "environment=prd" >> $GITHUB_OUTPUT
            echo "stacksuffix=" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "CheckPt B - main branch + dev"
            echo "environment=prd" >> $GITHUB_OUTPUT
            echo "stacksuffix=" >> $GITHUB_OUTPUT
          else
            echo "CheckPt C - other branch"
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "stacksuffix=-dev" >> $GITHUB_OUTPUT
          fi
      - run: |
          echo ${{ steps.vars.outputs.environment }}
          echo ${{ steps.vars.outputs.stacksuffix }}
