name: test-add-mask

on:
  push:
    paths:
      - .github/workflows/test-add-mask.yaml

defaults:
  run:
    shell: bash

jobs:
  test-add-mask-env:
    name: Test add-mask on env
    runs-on: ubuntu-latest
    env:
      JOB_1_VAR: job_1_val_value
    steps:
      - name: Mask the env
        run: |
          echo "::add-mask::$JOB_1_VAR"

      - name: Use the env
        run: |
          echo "$JOB_1_VAR"

  test-add-mask-env-using-GITHUB_ENV:
    name: Test add-mask on env 2 using GITHUB_ENV
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        run: |
          echo "action_state=$(ls)" >> $GITHUB_ENV
      - name: Mask the value
        run: |
          echo "::add-mask::$action_state"
      - name: Use the value
        run: |
          echo "${{ env.action_state }}"

  test-add-mask-step-output:
    name: Test add-mask on step output
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Set the value
        id: VpcInfo
        run: |
          echo "::set-output name=vpcid::vpc-11111111"
      - name: Mask the value
        run: |
          echo "::add-mask::${{ steps.VpcInfo.outputs.vpcid }}"
      - name: Use the value (output ***)
        run: |
          echo ${{ steps.VpcInfo.outputs.vpcid }}
