name: test-cdk-deploy

on:
  push:
    paths:
      - .github/workflows/test-cdk-deploy.yaml

defaults:
  run:
    shell: bash

jobs:
  deploy-cdk-app:
    name: Deploy CDK App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up CDK v2
        run: |
          sudo apt-get install -y nodejs
          sudo npm install -g aws-cdk@next

      - name: Set up deployment environment
        run: |
          python3 -m pip install -U pip
          echo "INFO: cdk version: $(cdk --version)"
          echo "INFO: python3 version: $(python3 --version)"
          echo "INFO: pip version: $(pip --version)"
          echo "INFO: Creating virtualenv env"
          python3 -m pip install --user virtualenv
          python3 -m venv env

      - name: Install requirements
        run: |
          source env/bin/activate
          echo "INFO: Activated venv: $(which python)"
          echo "TODO: pip install"
          deactivate

      # cdk deploy ${{ env.APP_NAME }} --require-approval never
