name: test-multi-set-output

on:
  workflow_dispatch:
    inputs:
      deploystage:
        description: 'Which AWS account to deploy into [dev, prd]?'
        required: true
        default: 'dev'

defaults:
  run:
    shell: bash

jobs:
  job-1:
    name: Running job-1
    runs-on: ubuntu-20.04
    steps:
      - id: VpcInfo
        run: |
          if [[ "${{ github.event.inputs.deploystage }}" == "prd" ]]
          then
            echo "::set-output name=vpcid::vpc-11111111"
            echo "::set-output name=subnetid::subnet-11111111"
          elif [[ "${{ github.event.inputs.deploystage }}" == "dev" ]]
          then
            echo "::set-output name=vpcid::vpc-22222222"
            echo "::set-output name=subnetid::subnet-22222222"
          else
            exit 1
          fi
      - run: |
          echo ${{ steps.VpcInfo.outputs.subnetid }}
          echo ${{ steps.VpcInfo.outputs.vpcid }}
