name: test-yamllint

on:
  push:
    paths:
      - .github/linters/.yaml-lint.yaml
      - .github/workflows/test-diff.yaml

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint with common config
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint
        run: yamllint -c ./.github/linters/.yaml-lint.yaml .github/

  lint-without-config:
    name: Run yamllint without config
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint
        run: yamllint -d "{extends: relaxed, rules: {line-length: disable}}" .github/
