name: test-workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      accountid:
        description: ID of the AWS account to deploy into
        required: true
      region:
        description: Target deployment region
        default: 'ap-southeast-2'
        required: true
      stage:
        description: Deployment stage
        type: choice
        default: prd
        options:
          - dev
          - prd
      use-emoji:
        description: Include 🎉🤣 emojis
        type: boolean
      environment:
        description: Environment to run tests against
        type: environment
        required: true

defaults:
  run:
    shell: bash

jobs:
  echo-parameters:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - run: echo accountid ${{ github.event.inputs.accountid }}
      - run: echo region ${{ github.event.inputs.region }}
      - run: echo stage ${{ github.event.inputs.stage }}
      - run: echo use-emoji ${{ github.event.inputs.use-emoji }}
      - run: echo environment ${{ github.event.inputs.environment }}

  test-boolean-input:
    runs-on: ubuntu-latest
    needs: [echo-parameters]
    steps:
      - if: ${{ github.event.inputs.use-emoji == "true" }}
        run: |
          echo INFO: use-emoji = true
      - if: ${{ github.event.inputs.use-emoji == "false" }}
        run: |
          echo INFO: use-emoji = false
      - if: ${{ github.event.inputs.use-emoji == "True" }}
        run: |
          echo INFO: use-emoji = True
      - if: ${{ github.event.inputs.use-emoji == "False" }}
        run: |
          echo INFO: use-emoji = False
