name: test-secrets

on:
  workflow_dispatch:
    inputs:
      deploystage:
        description: Deployment stage
        type: choice
        default: DEV
        options:
          - DEV
          - TST

defaults:
  run:
    shell: bash

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets[format('TEST_SECRETS_{0}', inputs.deploystage)] }}

  job-2:
    env:
      JOB_2_TEST: ${{ secrets[format('TEST_SECRETS_{0}', inputs.deploystage)] }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.JOB_2_TEST }}

  job-3:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "JOB_3_TEST=${{ secrets[format('TEST_SECRETS_{0}', inputs.deploystage)] }}" >> $GITHUB_ENV
      - run:
          echo ${{ env.JOB_3_TEST }}

  job-4-expected-fail:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets[format('TEST_SECRETS_NOTEXIST_{0}', inputs.deploystage)] }}
