name: test-multi-set-output

on:
  workflow_dispatch:
    inputs:
      deploystage:
        description: 'Which AWS account to deploy into [dev, prd]?'
        required: true
        default: 'dev'

defaults:
  run:
    shell: bash

jobs:
  job-1:
    name: Running job-1
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ github.event.inputs.deploystage }}" == "prd" ]]; then
            echo "stacksuffix=" >> $GITHUB_ENV
          else
            echo "stacksuffix=-dev" >> $GITHUB_ENV
          fi
      - run: |
          echo hello${{ env.stacksuffix }}-world
