name: test-env-file-to-github-env
on:
  push:
    paths:
      - .github/workflows/test-env-file-to-github-env.yaml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  job-1:
    name: Running job-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cat .github/workflows/_test1.env >> $GITHUB_ENV

      - run: echo "(${{ env.VAR_STAGE }})"

      - run: echo "(${{ env.VAR_STAGE_2 }})"

      - run: echo "(${{ env.VAR_CRON_1 }})"
        continue-on-error: true

      - run: echo "(${{ env.VAR_CRON_2 }})"
